### ISSUE TITLE
Taking too much time to connect the A200 device

### ISSUE THREAD

**Issue by rishabhbsdei** [CardFlight/cardflight-android#11]
After update of SDK cardflight-v3.2.3 ,its taking to much time to make connection  with A200 device . I also have A100 but its working fine with that. I am facing this problem after this update .Please check.

**Comment by austinodell** [comment]
Hi Rishabh,

Are you making a call to `setPreferredReader`?

Thanks,
Austin

**Comment by rishabhbsdei** [comment]
No ,I am not making a call to setPreferredReader and also I need both devices to configure with my app (A100,A200).

**Comment by rishabhbsdei** [comment]
Hi Austin
After your reply I made some changes in code as you suggest
 Reader.getDefault(this).setPreferredReader(ReaderType.A200_READER ).
                setPreferredReader(ReaderType.A100_READER)
                .setDeviceHandler(this);
Now its not connecting with A200 and working fine with A100  reader .

**Comment by austinodell** [comment]
Hi Rishabh,

The autoConfigHandler can be ignored in your case as that is only used with the Shuttle reader.

You should only be calling `setPreferredReader()` one time, for example:
```
Reader.getDefault(this)
    .setDeviceHandler(this)
    .setPreferredReader(ReaderType.A200_READER);
```

However, if you are designing an app for a mixed reader environment, I highly recommend saving the last used reader type per device and using that to speed up the connection process.

What device are you using that you are not able to connect with the A200? Are you sure that the A200 is charged, often times they will not work well when they are getting low on battery–including not connecting or dropping connection frequently.

Thanks,
Austin

**Comment by rishabhbsdei** [comment]
Hi Austin 
Thanks for your quick response.
Yes A200 is start connecting now ,this may be the issue of low battery .
As per my requirement ,I have to connect both of devices (A100,A200) with my app. So should I need to use setPreferredReader(ReaderType.UNKNOWN); in that case ?
And also if I added both preferred readers setPreferredReader(ReaderType.A200_READER ).
setPreferredReader(ReaderType.A100_READER) ,it connects with both but take more time to connect with A200 as compared with A100.
Please suggest me .

Thanks
Rishabh

**Comment by austinodell** [comment]
Hi Rishabh,

Glad to hear your A200 is working now.  As for needing to connect to multiple devices, my recommendation is to either not set a preferred reader or set it to the A100 if that is the more common reader.  Unless otherwise specified, the A200 is used as the preferred reader.  If you want to optimize connection times, though, you may want to save the most recently used reader per device using something like a SharedPreference and using that reader with `setPreferredReader(ReaderType)`.

You should only use one preferred reader as calling both will only use the last one.

Thanks,
Austin

**Comment by rishabhbsdei** [comment]
Hi Austin
Thanks for your response .It is really helpful .

Regards
Rishabh
