### ISSUE TITLE
Issue in CardSwipe with A200 Device

### ISSUE THREAD

**Issue by rishabhbsdei** [CardFlight/cardflight-android#13]
Hi Austin,
I am using your updated SDK for android 3.2.5. I am trying to make a swipe with A200 device . After successful swipe I should get response in     
public void readerCardResponse(Card card, CardFlightError cardFlightError) callback. I am getting response in this callback but this method is calling twice and giving a null response in second time . Its causing error in my app because I need to initialize Card object in readerCardResponse() method.
Please check my below logs
06-13 15:08:50.375 4978-4978/com.parkjockey.operator.staging E/Debug: readerCardResponse - Card com.getcardflight.models.Card@9e0bd3a
06-13 15:08:50.529 4978-4978/com.parkjockey.operator.staging E/Price: 100
06-13 15:08:50.532 4978-4978/com.parkjockey.operator.staging I/CardFlight: [Card.chargeCard] Card chargeCard
06-13 15:08:50.541 4978-4978/com.parkjockey.operator.staging V/CardFlight: [Card.chargeCard] Card: chargeCard: Card data is a from a swipe
06-13 15:08:50.546 4978-4978/com.parkjockey.operator.staging V/CardFlight: [cz.a] onReturnCheckCardResult: MCR
06-13 15:08:52.729 4978-4978/com.parkjockey.operator.staging V/CardFlight: [cz.m] onPowerDown
06-13 15:08:52.734 4978-4978/com.parkjockey.operator.staging V/CardFlight: [da.n] swipeTimeout
06-13 15:08:52.737 4978-4978/com.parkjockey.operator.staging E/Debug: readerCardResponse - Card null

Please fix this issue . Also this null response is again calling if I disconnect the  card reader ,check logs below
06-13 15:10:43.214 7586-7586/com.parkjockey.operator.staging E/Debug: readerIsDisconnected
06-13 15:10:43.231 7586-7586/com.parkjockey.operator.staging V/CardFlight: [cz.t] transaction state=WAITING_FOR_DIP
06-13 15:10:43.241 7586-7586/com.parkjockey.operator.staging E/Debug: readerCardResponse - Card null

Thanks, 
Rishabh

**Comment by austinodell** [comment]
Hi Rishabh,

Thank you for letting us know about this issue. It will be fixed in the next release.  In general, though, you should check if the CardFlightError is populated and if it is, don't try to use the Card object as it will be null. Instead you should display this error or handle it in some other way.

Thanks,
Austin

**Comment by rishabhbsdei** [comment]
Is this resolved?

**Comment by austinodell** [comment]
Hi Rishabh,

It is normal to receive a readerCardResponse with card set to null and an error populated, so you should always check for this.  What was the error you were receiving after a successful swipe?

Thanks,
Austin
