### ISSUE TITLE
Error in Refund

### ISSUE THREAD

**Issue by rishabhbsdei** [CardFlight/cardflight-android#14]
I am receiving 520 error code if I try to refund from my application . It was working fine in previous SDK's.
please check this issue.

**Comment by austinodell** [comment]
Hi Rishabh,

Could you send me the request you are making?

Thanks,
Austin

**Comment by rishabhbsdei** [comment]
Hi Austin 
Thanks for reply
I am suing your code to refund amount from app
 Charge.processRefund(model.token, model.amount, new CardFlightPaymentHandler() {
                        @Override
                        public void transactionSuccessful(Charge charge) {
                            OperatorBookingDetail.this.hideProgressBar();
                            request.token = charge.getToken();
                            cancelBooking(request);
                        }

                        @Override
                        public void transactionFailed(CardFlightError cardFlightError) {
                            OperatorBookingDetail.this.hideProgressBar();
                            Toast.makeText(OperatorBookingDetail.this, cardFlightError.getMessage() + "", Toast.LENGTH_SHORT).show();
                        }
                    });
                }

But I am getting 520 error code from your side. It was working fine

**Comment by austinodell** [comment]
Hi Rishabh,

Could you verify the amount you are sending and that the token is populated correctly?  I am going to take a look at this today.

Thanks,
Austin

**Comment by rishabhbsdei** [comment]
I am sending the correct amount. Like for 1 dollar ,I am sending 100

**Comment by austinodell** [comment]
Hi Rishabh,

I just wanted to confirm the issue you are having does exist and for now there is no work around.  You can expect an update very soon to fix this.  This issue is also present for voids.

Thanks,
Austin

**Comment by austinodell** [comment]
The update has been pushed
