### ISSUE TITLE
Cannot resolve all symbol from Cardflight SDK

### ISSUE THREAD

**Issue by trankimhieu** [CardFlight/cardflight-android#15]
Hi CF team.

When I add CF SDK to our project, With few previews version, everything is OK but from latest two version, We are facing a problem like this one
![android-tend ag-pos - android studio 2 2 2016-06-29 16-59-22](https://cloud.githubusercontent.com/assets/310085/16448273/d03850ca-3e1a-11e6-9898-a46d80f75469.png)
and this one
![android-tend ag-pos - android studio 2 2 2016-06-29 16-59-45](https://cloud.githubusercontent.com/assets/310085/16448282/dd3ce5e2-3e1a-11e6-8407-2979d711658c.png)
This is how do I config project
![android-tend ag-pos - android studio 2 2 2016-06-29 17-01-18](https://cloud.githubusercontent.com/assets/310085/16448330/169c9954-3e1b-11e6-9798-2db5f1dfc5c4.png)

I think problems come from code obfuscation. And I think you guys already used Proguard to do code obfuscation and Android Studio can not scan class name and public method. So please help me explain this one and can we have any action to make SDK have more usability.

**Comment by austinodell** [comment]
Hi Hieu,

Sorry to hear you're having this issue.  Just to make sure, you've added `compile project(':cardflight-android')` to your dependencies in your app's `build.gradle` file, correct?  If so, could you share any other obfuscation related details about your app?

I have double checked and verified that the methods you are trying to access are not obfuscated and available to use.

Thanks,
Austin

**Comment by trankimhieu** [comment]
![android-tend ag-pos - android studio 2 2 prev 2016-06-30 11-15-58](https://cloud.githubusercontent.com/assets/310085/16476694/ff067866-3eb3-11e6-9581-23ca059146a7.png)
![android-tend ag-pos - android studio 2 2 preview 4 2016-06-30 11-16-15](https://cloud.githubusercontent.com/assets/310085/16476700/11a58f70-3eb4-11e6-9147-1a4b8f996e1f.png)

And above issue has remained.
I don't use any Proguard or obfuscation method for now.

**Comment by austinodell** [comment]
I've never seen anyone have an issue with not being able to access the public methods.  Can you use a jar decompiler to verify that you can see the methods?  JD-GUI is a pretty good one.

Other than that, sometimes gradle needs to be "refreshed".  Try running `./gradlew clean` from the command line in the project's directory.

**Comment by austinodell** [comment]
Has this been resolved?
