### ISSUE TITLE
CardFlight issue urgent

### ISSUE THREAD

**Issue by ankushsdei** [CardFlight/cardflight-android#16]
Hello Austin,

                   Today we were testing with CardFlight android sdk 3.2.6 and we found some bugs during testing as mentioned below:-
1) First of all when we connect the A100 machine to our android device then it takes much time as for connecting compared to A200 machine.
2) In case of swipe, if our user swipes the card and INTERNET goes away then it shows "No internet connection" popup message from the cardflight. But this is not happening while our user dip the card when there is no internet present in his android device.
3) In case of Dip, if a user cancel his transaction then it gives "Unkonwn error occured" message in CardFlighMessage.

Thanks
Ankush

**Comment by ankushsdei** [comment]
Hello Austin,
                      Today we faced one more strange bug while testing with A200 reader that supports both Swipe and Dip features. What exactly we are doing is explained below:-

We call this method Reader.getDefault(this).beginEMVTransaction(intPrice, chargeDetailsHashMap);  and our A200 reader was connected to the android device. Is it possible to swipe the card instead of dip when we called above said method with A200?

Because when we were trying to swipe our card with A200 chip card reader machine then it says "Dip Card". The eaxct message in our logcat was emvMessage37: Dip card.

Thanks
Ankush

**Comment by austinodell** [comment]
Hi Ankush,

Thanks for sending these to us, I will take a look at correct any issues I find.

As for the connection time, that can be minimized by simply setting the preferred reader by calling
```
Reader.getDefault(context).setPreferredReader(ReaderType.A100_READER)
```
If you need to use both readers, I would recommend having each device store (in something like a SharedPreference) the last used reader and always set that as the preferred.  That should drastically reduce connection times.

What callback are you receiving "No internet connection" from when you swipe a card?  Would you mind attaching logs for both swipe and dip?

What method are you using the cancel the transaction?

And if you are calling `beginEMVTransaction`, then you will be forced to dip a card if it has a chip.  If you do not want to dip cards, you can call `beginSwipe` instead.

Thanks,
Austin

**Comment by ankushsdei** [comment]
What method are you using the cancel the transaction?

Reply:-  For cancel the transaction we are calling  Reader.getDefault(mContext).emvProcessTransaction(false);

And afterwards we are calling Reader.getDefault(PaymentOptionsActivity.this).restartReader(ReaderType.A200_READER);  and  this method seems not to be working 2 days ago. But today I checked this and it starts working.

**Comment by ankushsdei** [comment]
As for the connection time, that can be minimized by simply setting the preferred reader by calling
Reader.getDefault(context).setPreferredReader(ReaderType.A100_READER)

Reply:-  Yes we tried calling your suggested above method into the Application class. For the first time when we go to our Payment Screen then it immediately connects A100 reader and becomes ready to swipe. But we remove and reconnects the reader 2 or mores times on the same screen and by go back from screen then it shows "Swipe Error" and sometimes "Swipe Timeout Error". Below are our log-cat console messages:-

07-01 11:53:02.385 25664-25664/com.parkjockey.operator.staging E/Debug: readerIsConnecting 
07-01 11:53:02.391 25664-25664/com.parkjockey.operator.staging V/CardFlight: [da.e] trying rambler
07-01 11:53:12.337 25664-25664/com.parkjockey.operator.staging V/CardFlight: [da.m] swipeFailed
07-01 11:53:12.338 25664-25664/com.parkjockey.operator.staging E/Debug: readerCardResponse - Card null
07-01 11:53:12.472 25664-25664/com.parkjockey.operator.staging V/CardFlight: [da.l] readyToSwipe
07-01 11:53:29.788 25664-25664/com.parkjockey.operator.staging V/CardFlight: [cx.i] timeout
07-01 11:53:29.789 25664-25664/com.parkjockey.operator.staging V/CardFlight: [da.n] swipeTimeout
07-01 11:53:29.790 25664-25664/com.parkjockey.operator.staging E/Debug: readerCardResponse - Card null

**Comment by austinodell** [comment]
Is it able to connect after the first time on that same screen?  Or does it just give the error `Swipe Timeout Error`?

**Comment by sumeet3100** [comment]
It gives swipe Timeout error

**Comment by sumeet3100** [comment]
This is my log
07-01 10:15:23.425 7271-7271/com.parkjockey.operator.staging V/CardFlight: [cz.a] onError(TIMEOUT)
07-01 10:15:23.425 7271-7271/com.parkjockey.operator.staging V/CardFlight: [da.g] deviceTimeout
07-01 10:15:23.425 7271-7271/com.parkjockey.operator.staging V/CardFlight: [da.e] trying rambler
07-01 10:15:23.425 7271-7271/com.parkjockey.operator.staging V/CardFlight: [cz.t] transaction state=NEW
07-01 10:15:23.435 30980-30980/com.parkjockey.operator V/CardFlight: [cz.a] onError(TIMEOUT)
07-01 10:15:23.435 30980-30980/com.parkjockey.operator V/CardFlight: [da.g] deviceTimeout
07-01 10:15:23.435 30980-30980/com.parkjockey.operator V/CardFlight: [da.e] trying rambler
07-01 10:15:23.435 30980-30980/com.parkjockey.operator V/CardFlight: [cz.t] transaction state=NEW
07-01 10:15:23.855 7271-7271/com.parkjockey.operator.staging V/CardFlight: [da.g] deviceTimeout
07-01 10:15:23.855 7271-7271/com.parkjockey.operator.staging V/CardFlight: [da.f] trying shuttle

**Comment by austinodell** [comment]
Are you able to replicate this behavior with the A200?

**Comment by sumeet3100** [comment]
yes both the readers are giving timeout

**Comment by austinodell** [comment]
Could it be possible that you have created multiple reader instances?  Also, do you have any other application open in the background that is also using the microphone?

**Comment by sumeet3100** [comment]
No there is only one instance for the reader. My device has only one app and there is no other application which will be using microphone.

**Comment by austinodell** [comment]
Are you calling `Reader.getDefault` from the main thread or a background thread?

**Comment by sumeet3100** [comment]
We are not calling this method Austin.

**Comment by austinodell** [comment]
How are you initializing the Reader object?

**Comment by ankushsdei** [comment]
Hello Austin,

               Yes we are initializing the Reader object by calling this method   Reader.getDefault(this)
                .setDeviceHandler(this);  in our Application class.

Thanks,
Ankush

**Comment by austinodell** [comment]
Could you give me a code sample of everything you are calling on the Reader object so I can replicate the issue and solve this bug?

Thanks,
Austin

**Comment by austinodell** [comment]
Has this been resolved?

**Comment by PratibhaSarode** [comment]
Hello Austin,
                   I am using cardflight-v4-android and I am facing swipe_error. Please help.

Thank you,
Pratibha
