### ISSUE TITLE
Issue with CardFlight Sdk when user connects headphones instead of reader

### ISSUE THREAD

**Issue by ankushsdei** [CardFlight/cardflight-android#17]
Hello Austin,

                   Today while testing with the card flight one more strange issue poped up. When we connect the headphones instead of any of our readers(A100, A200) then it starts producing beep sound. Even if we send our application to the background still it gives beep sound. Then we downloaded Android Card Flight Demo from Git-hub the same problem was also happening there.

**Comment by austinodell** [comment]
Hi Ankush,

You should warn the user before starting the Reader class because the readers you connect appear as headphones and there is no way to distinguish a headphone vs. a reader.  And as I'm sure you saw, it produces a very loud noise through the speaker.

Thanks,
Austin
