### ISSUE TITLE
SWIPE_ERROR in cardflight-v4-android

### ISSUE THREAD

**Issue by PratibhaSarode** [CardFlight/cardflight-android#19]
Hello Austin,
I am using cardflight-v4-android and I am facing swipe_error many times. Sometimes I have to swipe 20 - 25 times, then I get swipe completed. Please help.

Thank you,
Pratibha

**Comment by austinodell** [comment]
Hi Pratibha,

Please contact support@cardflight.com for assistance.

Austin
