### ISSUE TITLE
New version of library doesn't work with Android API 10

### ISSUE THREAD

**Issue by ulyandmi** [CardFlight/cardflight-android#2]
...
01-14 12:55:58.229: E/AndroidRuntime(9197): at android.view.View.performClick(View.java:2485)
01-14 12:55:58.229: E/AndroidRuntime(9197): at android.view.View$PerformClick.run(View.java:9080)
01-14 12:55:58.229: E/AndroidRuntime(9197): at android.os.Handler.handleCallback(Handler.java:587)
01-14 12:55:58.229: E/AndroidRuntime(9197): at android.os.Handler.dispatchMessage(Handler.java:92)
01-14 12:55:58.229: E/AndroidRuntime(9197): at android.os.Looper.loop(Looper.java:123)
01-14 12:55:58.229: E/AndroidRuntime(9197): at android.app.ActivityThread.main(ActivityThread.java:3683)
01-14 12:55:58.229: E/AndroidRuntime(9197): at java.lang.reflect.Method.invokeNative(Native Method)
01-14 12:55:58.229: E/AndroidRuntime(9197): at java.lang.reflect.Method.invoke(Method.java:507)
01-14 12:55:58.229: E/AndroidRuntime(9197): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
01-14 12:55:58.229: E/AndroidRuntime(9197): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
01-14 12:55:58.229: E/AndroidRuntime(9197): at dalvik.system.NativeStart.main(Native Method)
01-14 12:55:58.229: E/AndroidRuntime(9197): Caused by: java.lang.reflect.InvocationTargetException
01-14 12:55:58.229: E/AndroidRuntime(9197): at java.lang.reflect.Constructor.constructNative(Native Method)
01-14 12:55:58.229: E/AndroidRuntime(9197): at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
01-14 12:55:58.229: E/AndroidRuntime(9197): at android.view.LayoutInflater.createView(LayoutInflater.java:505)
01-14 12:55:58.229: E/AndroidRuntime(9197): ... 24 more
01-14 12:55:58.229: E/AndroidRuntime(9197): Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class com.getcardflight.views.CardIcon
01-14 12:55:58.229: E/AndroidRuntime(9197): at android.view.LayoutInflater.createView(LayoutInflater.java:518)
01-14 12:55:58.229: E/AndroidRuntime(9197): at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
01-14 12:55:58.229: E/AndroidRuntime(9197): at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
01-14 12:55:58.229: E/AndroidRuntime(9197): at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
01-14 12:55:58.229: E/AndroidRuntime(9197): at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
01-14 12:55:58.229: E/AndroidRuntime(9197): at com.getcardflight.views.PaymentView.b(Unknown Source)
01-14 12:55:58.229: E/AndroidRuntime(9197): at com.getcardflight.views.PaymentView.<init>(Unknown Source)
01-14 12:55:58.229: E/AndroidRuntime(9197): ... 27 more
01-14 12:55:58.229: E/AndroidRuntime(9197): Caused by: java.lang.reflect.InvocationTargetException
01-14 12:55:58.229: E/AndroidRuntime(9197): at java.lang.reflect.Constructor.constructNative(Native Method)
01-14 12:55:58.229: E/AndroidRuntime(9197): at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
01-14 12:55:58.229: E/AndroidRuntime(9197): at android.view.LayoutInflater.createView(LayoutInflater.java:505)
01-14 12:55:58.229: E/AndroidRuntime(9197): ... 33 more
01-14 12:55:58.229: E/AndroidRuntime(9197): Caused by: java.lang.NoClassDefFoundError: android.animation.ObjectAnimator
01-14 12:55:58.229: E/AndroidRuntime(9197): at com.getcardflight.views.CardIcon.a(Unknown Source)
01-14 12:55:58.229: E/AndroidRuntime(9197): at com.getcardflight.views.CardIcon.<init>(Unknown Source)
01-14 12:55:58.229: E/AndroidRuntime(9197): ... 36 more

**Comment by pcdroidski** [comment]
The CardFlight SDK is only compatible with API greater than or equal to 11. API 10 will not work.
