### ISSUE TITLE
3.0.6 SDK crash on card charge

### ISSUE THREAD

**Issue by ryazmin** [CardFlight/cardflight-android#6]
Fatal Exception: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer 
       at com.getcardflight.util.n.a(SourceFile:22) 
       at com.getcardflight.models.Card.chargeCard(SourceFile:217) 

Looks like now the SDK expects charge amount in cents as Integer (599 for example),
but older versions expect amount in dollars as Double (5.99 for example).

But documentation still says: amount - Double containing amount to charge

And android demo also passing double as charge amount, so will crash with 3.0.6
https://github.com/CardFlight/android-demo/blob/master/android-demo/src/com/example/cardflight/fragments/ReaderDemoFragment.java#L671

**Comment by austinodell** [comment]
Hi Roman,

Thank you for reaching out. You are correct, make sure you are sending an Integer in the HashMap with key "amount". Thank you for pointing out that the documentation was not correct, we will update this ASAP.
