### ISSUE TITLE
3.0.6 SDK, transactionFailed error Invalid Credentials, code 500

### ISSUE THREAD

**Issue by ryazmin** [CardFlight/cardflight-android#7]
When trying to charge a card on SDK 3.0.6,
getting transactionFailed callback with error message: "Invalid Credentials" and error code: 500.

CardFlight correctly initialized with api and account tokens
by calling setApiTokenAndAccountToken method.
Tokens was valid before upgrading SDK to 3.0.6.

**Comment by austinodell** [comment]
Hi Roman,

This issue has been fixed in the latest version.

Thanks,
Austin
